imagenet_templates_small = [
    "a photo of a {}",
    "a rendering of a {}",
    "a cropped photo of the {}",
    "the photo of a {}",
    "a photo of a clean {}",
    "a photo of a dirty {}",
    "a dark photo of the {}",
    "a photo of my {}",
    "a photo of the cool {}",
    "a close-up photo of a {}",
    "a bright photo of the {}",
    "a cropped photo of a {}",
    "a photo of the {}",
    "a good photo of the {}",
    "a photo of one {}",
    "a close-up photo of the {}",
    "a rendition of the {}",
    "a photo of the clean {}",
    "a rendition of a {}",
    "a photo of a nice {}",
    "a good photo of a {}",
    "a photo of the nice {}",
    "a photo of the small {}",
    "a photo of the weird {}",
    "a photo of the large {}",
    "a photo of a cool {}",
    "a photo of a small {}",
]

imagenet_style_templates_small = [
    "a painting in the style of {}",
    "a rendering in the style of {}",
    "a cropped painting in the style of {}",
    "the painting in the style of {}",
    "a clean painting in the style of {}",
    "a dirty painting in the style of {}",
    "a dark painting in the style of {}",
    "a picture in the style of {}",
    "a cool painting in the style of {}",
    "a close-up painting in the style of {}",
    "a bright painting in the style of {}",
    "a cropped painting in the style of {}",
    "a good painting in the style of {}",
    "a close-up painting in the style of {}",
    "a rendition in the style of {}",
    "a nice painting in the style of {}",
    "a small painting in the style of {}",
    "a weird painting in the style of {}",
    "a large painting in the style of {}",
]

def scene_prompts(unique_token='',class_token=''): 
    return [
        'a photo of a {0}{1}'.format(unique_token, class_token),
        'a photo of a {0}{1} in the jungle'.format(unique_token, class_token),
        'a photo of a {0}{1} in the snow'.format(unique_token, class_token),
        'a photo of a {0}{1} on the beach'.format(unique_token, class_token),
        'a photo of a {0}{1} on a cobblestone street'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of pink fabric'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of a wooden floor'.format(unique_token, class_token),
        'a photo of a {0}{1} with a city in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} with a mountain in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} with a blue house in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of a purple rug in a forest'.format(unique_token, class_token),
        'a photo of a {0}{1} with a wheat field in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} with a tree and autumn leaves in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} with the Eiffel Tower in the background'.format(unique_token, class_token),
        'a photo of a {0}{1} floating on top of water'.format(unique_token, class_token),
        'a photo of a {0}{1} floating in an ocean of milk'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of green grass with sunflowers around it'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of a mirror'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of the sidewalk in a crowded street'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of a dirt road'.format(unique_token, class_token),
        'a photo of a {0}{1} on top of a white rug'.format(unique_token, class_token),
        'a photo of a red {0}{1}'.format(unique_token, class_token),
        'a photo of a purple {0}{1}'.format(unique_token, class_token),
        'a photo of a shiny {0}{1}'.format(unique_token, class_token),
        'a photo of a wet {0}{1}'.format(unique_token, class_token),
        'a photo of a cube shaped {0}{1}'.format(unique_token, class_token),
        'a photo of a {0}{1} is running on the road'.format(unique_token, class_token)
        ]

def costume_prompts(unique_token='',class_token=''): 
    return [
        'a {0}{1} in the jungle'.format(unique_token, class_token),
        'a {0}{1} in the snow'.format(unique_token, class_token),
        'a {0}{1} on the beach'.format(unique_token, class_token),
        'a {0}{1} on a cobblestone street'.format(unique_token, class_token),
        'a {0}{1} on top of pink fabric'.format(unique_token, class_token),
        'a {0}{1} on top of a wooden floor'.format(unique_token, class_token),
        'a {0}{1} with a city in the background'.format(unique_token, class_token),
        'a {0}{1} with a mountain in the background'.format(unique_token, class_token),
        'a {0}{1} with a blue house in the background'.format(unique_token, class_token),
        'a {0}{1} on top of a purple rug in a forest'.format(unique_token, class_token),
        'a {0}{1} wearing a red hat'.format(unique_token, class_token),
        'a {0}{1} wearing a santa hat'.format(unique_token, class_token),
        'a {0}{1} wearing a rainbow scarf'.format(unique_token, class_token),
        'a {0}{1} wearing a black top hat and a monocle'.format(unique_token, class_token),
        'a {0}{1} in a chef outfit'.format(unique_token, class_token),
        'a {0}{1} in a firefighter outfit'.format(unique_token, class_token),
        'a {0}{1} in a police outfit'.format(unique_token, class_token),
        'a {0}{1} wearing pink glasses'.format(unique_token, class_token),
        'a {0}{1} wearing a yellow shirt'.format(unique_token, class_token),
        'a {0}{1} in a purple wizard outfit'.format(unique_token, class_token),
        'a red {0}{1}'.format(unique_token, class_token),
        'a purple {0}{1}'.format(unique_token, class_token),
        'a shiny {0}{1}'.format(unique_token, class_token),
        'a wet {0}{1}'.format(unique_token, class_token),
        'a cube shaped {0}{1}'.format(unique_token, class_token)
    ]
    

def imagenet_prompt_list(unique_token='', class_token=''):
    return [
        "a photo of a {0}{1}".format(unique_token, class_token),
        "a rendering of a {0}{1}".format(unique_token, class_token),
        "a cropped photo of the {0}{1}".format(unique_token, class_token),
        "the photo of a {0}{1}".format(unique_token, class_token),
        "a photo of a clean {0}{1}".format(unique_token, class_token),
        "a photo of a dirty {0}{1}".format(unique_token, class_token),
        "a dark photo of the {0}{1}".format(unique_token, class_token),
        "a photo of my {0}{1}".format(unique_token, class_token),
        "a photo of the cool {0}{1}".format(unique_token, class_token),
        "a close-up photo of a {0}{1}".format(unique_token, class_token),
        "a bright photo of the {0}{1}".format(unique_token, class_token),
        "a cropped photo of a {0}{1}".format(unique_token, class_token),
        "a photo of the {0}{1}".format(unique_token, class_token),
        "a good photo of the {0}{1}".format(unique_token, class_token),
        "a photo of one {0}{1}".format(unique_token, class_token),
        "a close-up photo of the {0}{1}".format(unique_token, class_token),
        "a rendition of the {0}{1}".format(unique_token, class_token),
        "a photo of the clean {0}{1}".format(unique_token, class_token),
        "a rendition of a {0}{1}".format(unique_token, class_token),
        "a photo of a nice {0}{1}".format(unique_token, class_token),
        "a good photo of a {0}{1}".format(unique_token, class_token),
        "a photo of the nice {0}{1}".format(unique_token, class_token),
        "a photo of the small {0}{1}".format(unique_token, class_token),
        "a photo of the weird {0}{1}".format(unique_token, class_token),
        "a photo of the large {0}{1}".format(unique_token, class_token),
        "a photo of a cool {0}{1}".format(unique_token, class_token),
        "a photo of a small {0}{1}".format(unique_token, class_token),
    ]
